-- Run this in Supabase SQL Editor to create the admins table

CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    name TEXT DEFAULT 'Admin',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default admin: admin@mail.com / admin123
INSERT INTO admins (email, password_hash, name)
VALUES ('admin@mail.com', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Admin')
ON CONFLICT (email) DO NOTHING;

-- Disable RLS so the admin panel can query this table
ALTER TABLE admins DISABLE ROW LEVEL SECURITY;
